config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'welcome/index'
  root 'welcome#index'
  put "/products/:id/publish", to: "products#publish"
  put "/products/:id/archive", to: "products#archive"
  resources :products
  resources :categories
  resources :users, only: [:show]
end

app/models/user.rb
# frozen_string_literal: true
require 'open-uri'
# User model with its relation to affair and validations.
class User < ApplicationRecord
  has_many :products

  has_one_attached :photo

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  validates :photo, presence: true
  validates :first_name, presence: true, length: { minimum: 2, maximum: 25 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[a-z\d\-_.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, uniqueness: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX }

  def self.from_omniauth(auth)
    image = open(auth.info.image)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.photo.attach(io: image, filename: 'photo.jpeg', content_type: image.content_type)
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end


  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users controller with the CRUD and other meodos.
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User was successfully created'
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :cellphone,
                                 :address, :photo)
  end
end

app/views/users/_form.html.erb
<div class="container w-25">
  <%= simple_form_for @user do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.input :cellphone %>
    <%= f.input :address %>
    <%= f.button :submit, class:"btn btn-primary" %>
    <%= link_to 'Back', users_path, class:"btn btn-primary" %>
    <br>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1 class="text-info title"> Edit User </h1><br>
  <%= render 'form' %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h1 class="text-info title"> Create a New Account </h1><br>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container w-50 shadow-lg p-4 mb-5 bg-white rounded">
  <h1 class="text-info title text-center">User information</h1>
  <br>
  <div class="well span8 offset2 p-3">
    <div class="row-fluid user-row">
    <div class="panel-body">
      <div class="row-fluid">
        <div class="span3 text-center">
        <% if @user.photo.attached? %>
          <%= image_tag( @user.photo, class:' w-50 h-25' ) %>
        <% end %>
        </div>
        <div class="span6">
          <table class="table table-condensed table-responsive
            table-user-information">
            <body>
              <tr>
                <td>Name: </td>
                <td><%=@user.first_name%></td>
              <tr>
              <tr>
                <td>Last name: </td>
                <td><%=@user.last_name%></td>
              <tr>
              <tr>
                <td>Email: </td>
                <td><%=@user.email %></td>
              <tr>
              <tr>
                <td>Registered since: </td>
                <td><%=@user.created_at%></td>
              <tr>
            </body>
          </table>
        </div>
      </div>
    </div>
  </div>
  <%=link_to 'Edit', edit_user_registration_path(current_user), class:"btn btn-primary"%>
  <%= link_to 'Back', products_path, class:"btn btn-primary" %>
</div>