config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'welcome/index'
  root 'welcome#index'
  put "/products/:id/publish", to: "products#publish"
  put "/products/:id/archive", to: "products#archive"
  resources :products
  resources :categories
  resources :users, only: [:show]
end

app/models/product.rb
# frozen_string_literal: true

# Product model with its respective validations.
class Product < ApplicationRecord
  include AASM

  has_and_belongs_to_many :categories

  belongs_to :user

  has_one_attached :image

  validates :name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :quantity, presence: true
  validates :price, presence: true

  aasm :column => 'status' do
    state :unpublished, initial: true
    state :published
    state :archived

    event :publish, after: :send_mail do
      transitions from: [:unpublished, :archived], to: :published
    end

    event :unpublished do
      transitions from: :published, to: :unpublished
    end

    event :archive do
      transitions from: [:published, :unpublished], to: :archived
    end
  end

  scope :product_by_user, ->(current_user) { where(user_id: current_user) }

  private

  def send_mail
    UserMailer.product_publish(self).deliver_later
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Product controller with the CRUD methods
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [ :show ]
  before_action :set_product, except:[ :index, :new, :create, :show ]

  def index
    @products = Product.product_by_user(current_user)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(products_params)
    @product.user_id = current_user.id
    if @product.save
      flash[:notice] = 'Product was successfully created'
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def publish
    @product.publish!
    redirect_to @product
  end

  def archive
    @product.archive!
    redirect_to @product
  end

  def update
    @product.user_id = current_user.id
    if @product.update(products_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def products_params
    params.require(:product).permit(:name, :description,
                                    :quantity, :price,
                                    :image, category_ids:[])
  end

  def set_product
    @product = Product.product_by_user(current_user).find(params[:id])
  end
end

app/views/products/_form.html.erb
<div class="container w-50 shadow-lg p-3 mb-5 bg-white rounded-lg border border-info">
  <h1 class="text-info title text-center"> <%= name %> Product </h1><br>
  <%= simple_form_for @product do |f| %>
    <%= f.file_field :image %><br>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.label "Categories: " %><br />
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div><br>
     <% end %>
    <%= f.input :quantity %>
    <%= f.input :price %>
    <%= f.button :submit, class:"btn btn-dark" %>
    <%= link_to 'Back', products_path, class:"btn btn-info" %>
    <br>
  <% end %>
</div>

app/views/products/edit.html.erb
<%= render "form", name:"Edit"%>

app/views/products/index.html.erb
<div class=" container w-50">
  <% @products.each do |product|%>
    <div class="card mb-3">
      <div class="row no-gutters">
        <div class="col-md-4">
          <% if product.image.attached? %>
            <%= image_tag( product.image, class:"card-img", style:'width: 180px') %>
          <% else %>
            <%= image_tag('gris.jpg', class:"card-img", style:'width: 180px') %>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="title"><%= product.name %></h5>
            <p class="card-text"><%= product.description %></p>
            <%= link_to 'show', product_path(product), class:"btn btn-info" %>
            <%= link_to 'edit', edit_product_path(product), class:"btn btn-dark" %>
            <% if product.may_publish? && product.may_archive? %>
              <%= link_to 'publish', "/products/#{product.id}/publish", class:"btn btn-success", method: :put %>
              <%= link_to 'Archive', "/products/#{product.id}/archive", class:"btn btn-secondary", method: :put %>
            <% elsif product.may_archive? %>
              <%= link_to 'Archive', "/products/#{product.id}/archive", class:"btn btn-secondary", method: :put %>
            <% else %>
              <%= link_to 'publish', "/products/#{product.id}/publish", class:"btn btn-success", method: :put %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<%= render "form", name:"New" %>

app/views/products/show.html.erb
<div class="container w-50 pricing-table pricing-three-column border border-info rounded shadow-lg p-3 mb-5 bg-white ">
  <div class="span4 p-1 pb-3">
    <div class="plan-name-silver row">
      <div class="col">
        <h2 class="text-info title"><%= @product.name %></h2>
        <span>$<%= @product.price%></span>
      </div>
      <div class="col">
       <% if @product.image.attached? %>
          <%= image_tag( @product.image, class:"p-0 mb-2 float-right", style:'width: 180px') %>
        <% else %>
          <%= image_tag('gris.jpg', class:"p-0 mb-2 float-right", style:'width: 180px') %>
        <% end %>
      </div>
    </div>
    <ul class="p-3">
      <li class="plan-feature text-info"><span>Description:</span> <%= @product.description %></li>
      <li class="plan-feature text-info"><span>Units available:</span> <%= @product.quantity %></li>
      <li class="plan-feature text-info"><span>Categories:</span></li>
      <% @product.categories.each do |category|%>
        <%= category.name %>
      <% end %>
      <li class="plan-feature text-info"><span>Seller:</span> <%= @product.user.first_name + " " + @product.user.last_name %></li>
      <li class="plan-feature text-info"><span>Cellphone:</span> <%= @product.user.cellphone%></li>
    </ul>
    <%= link_to 'Back', root_path, class:"btn btn-secondary text-center" %>
    <% if signed_in? && @product.user_id == current_user.id %>
      <%= link_to 'Edit', edit_product_path(@product), class:"btn btn-info aling-center" %>
    <% end %>
  </div>
</div>