config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'welcome/index'
  root 'welcome#index'
  put "/products/:id/publish", to: "products#publish"
  put "/products/:id/archive", to: "products#archive"
  resources :products
  resources :categories
  resources :users, only: [:show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application',
                             media: 'all',
                            'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
   <%= favicon_link_tag asset_path('shoppy.png') %>
  </head>

  <body>
    <nav class="navbar bg-dark navbar-dark pl-4">
      <%= link_to root_path, class:"title navbar-brand text-info" do %>
        <%= image_tag('shoppy.png',
                      style: 'width: 40px;',
                      class:"navbar-brand")%>
        Shoppy
      <% end %>
      <ul class="nav justify-content-end">
        <% if signed_in? %>
          <li class="nav nav-item">
            <div class="dropdown">
              <button class=" btn mr-2" type="button"
                                                id="dropdownMenuButton"
                                                data-toggle="dropdown"
                                                aria-haspopup="true"
                                                aria-expanded="false">
              <%= image_tag('sum2.png',style: 'width: 40px;', class:" p-0 mb-2") %>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'Add products', new_product_path, class:"dropdown-item" %>
                <%= link_to 'Add category', new_category_path, class:"dropdown-item" %>
              </div>
            </div>
          </li> 
          <li class="nav nav-item">
            <div class="dropdown">
              <button class="btn btn-secondary dropdown-toggle" type="button"
                                                                id="dropdownMenuButton"
                                                                data-toggle="dropdown"
                                                                aria-haspopup="true"
                                                                aria-expanded="false">
                <% if current_user.photo.attached? %>
                  <%= image_tag(current_user.photo, style: 'width: 30px;', class:"navbar-brand")%>
                <% else %>
                  <%= image_tag('photo.png', style: 'width: 30px;', class:"navbar-brand")%>
                <% end %>
                <%= current_user.first_name %> <%= current_user.last_name %>
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to 'My products', products_path, class:"dropdown-item" %>
                <%= link_to "Logout", destroy_user_session_path,
                                      class:"dropdown-item",
                                      method: :delete %>
                <%=link_to 'My profile', user_path(current_user), class:"dropdown-item"%>
              </div>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to "Log in", new_user_session_path,
                                class:"btn btn-info m-2 p-2" %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path,
                                 class:"btn btn-light m-2 p-2" %>
          </li>
        <% end %>
      </ul>
    </nav>
    <br>
    <% if notice %>
      <br>
      <div class="alert alert-primary p-2 container alert-dismissible fade show" role="alert">
        <%= notice%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% elsif alert %>
      <br>
      <div class="alert alert-warning p-2 container alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>